# fly.toml app configuration file generated for fleet-tracker-api on 2023-09-04T12:38:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fleet-tracker-api"
primary_region = "waw"
console_command = "php /var/www/html/artisan tinker"

[build]
  dockerfile = "docker/prod/Dockerfile"
  [build.args]
    PHP_VERSION = "8.3"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_NAME = "FleetTracker"
  APP_URL = "https://fleet-tracker-api.fly.dev"
  CACHE_DRIVER = "file"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/storage/database/database.sqlite"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  QUEUE_CONNECTION = "sync"
  SESSION_DRIVER = "cookie"
  SESSION_LIFETIME = "1440"
  SESSION_SECURE_COOKIE = "true"
  FRONTEND_URL = "https://fleet-tracker-umber.vercel.app"

[[mounts]]
  source = "storage_vol"
  destination = "/var/www/html/storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
